[phases.setup]
nixPkgs = [
  "nodejs",
  "chromium",
  "fontconfig",
  "glibc",
  "nss",
  "freetype",
  "libxshmfence",
  "libxrandr",
  "libxcomposite",
  "libxdamage",
  "libxext",
  "libxfixes",
  "libxrender",
  "libasound2"
]

[phases.build]
cmds = ["echo 'âœ… Chromium & Node.js installed'"]

[phases.start]
cmds = ["node index.js"]
